services:
  # Servicio de la aplicación Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myfavorites_app
    ports:
      - "8001:8000"
    volumes:
      - .:/var/www
      - /var/www/vendor
      - /var/www/node_modules
    env_file:
      - ./.env
    depends_on:
      - db

  # Servicio de la base de datos MySQL
  db:
    image: mysql:8.0
    container_name: myfavorites_db
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - myfavorites_db_data:/var/lib/mysql
    restart: always

volumes:
  myfavorites_db_data:
